spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis_plus_demo
    username: root
    password: 123456

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/xml/*.xml
server:
  port: 8081
